ml_web_app/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('prediction.urls')),
]

prediction/urls.py
from django.urls import path
from . import views

app_name = "predict"

urlpatterns = [
    path('', views.predict, name='prediction_page'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('results/', views.view_results, name='results'),
]

prediction/models.py
from django.db import models


class PredResults(models.Model):

    sepal_length = models.FloatField()
    sepal_width = models.FloatField()
    petal_length = models.FloatField()
    petal_width = models.FloatField()
    classification = models.CharField(max_length=30)

    def __str__(self):
        return self.classification

prediction/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults


def predict(request):
    return render(request, 'predict.html')


def predict_chances(request):

    if request.POST.get('action') == 'post':

        # Receive data from client
        sepal_length = float(request.POST.get('sepal_length'))
        sepal_width = float(request.POST.get('sepal_width'))
        petal_length = float(request.POST.get('petal_length'))
        petal_width = float(request.POST.get('petal_width'))

        # Unpickle model
        model = pd.read_pickle(r"C:\Users\bharat paliwal\Desktop\Python_OP\ML_Django\ML_into_Django\ml_web_app\new_model.pickle")
        # Make prediction
        result = model.predict([[sepal_length, sepal_width, petal_length, petal_width]])

        classification = result[0]

        PredResults.objects.create(sepal_length=sepal_length, sepal_width=sepal_width, petal_length=petal_length,
                                    petal_width=petal_width, classification=classification)

        return JsonResponse({'result': classification, 'sepal_length': sepal_length,
                                'sepal_width': sepal_width, 'petal_length': petal_length, 'petal_width': petal_width},
                            safe=False)


def view_results(request):
    # Submit prediction and show all
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

prediction/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Iris prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

prediction/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Sepal Length: <span id="sl"></span></div>
                <div>Sepal Width: <span id="sw"></span></div>
                <div>Petal Length: <span id="pl"></span></div>
                <div>Petal width: <span id="pw"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Iris Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="sepal_length">Sepal Length</label>
                    <input type="number" step="0.1" class="form-control" id="sepal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="Sepal Width">Sepal Width</label>
                    <input type="number" step="0.1" class="form-control" id="sepal_width" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_length">Petal Length</label>
                    <input type="number" step="0.1" class="form-control" id="petal_length" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="petal_width">Petal Width</label>
                    <input type="number" step="0.1" class="form-control" id="petal_width" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                sepal_length:$('#sepal_length').val(),
                sepal_width:$('#sepal_width').val(),
                petal_length:$('#petal_length').val(),
                petal_width:$('#petal_width').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['sepal_length']
                document.getElementById("sw").innerHTML = json['sepal_width']
                document.getElementById("pl").innerHTML = json['petal_length']
                document.getElementById("pw").innerHTML = json['petal_width']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

prediction/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Sepal length</th>
                <th scope="col">Sepal width</th>
                <th scope="col">Petal length</th>
                <th scope="col">Petal width</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.sepal_length }}</td>
                    <td>{{ data.sepal_width }}</td>
                    <td>{{ data.petal_length }}</td>
                    <td>{{ data.petal_width }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}